repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: lua-check
        name: lua-check
        entry: luacheck data/import-theme/
        language: system
        pass_filenames: false
