services:
  pg_featureserv:
    image: pramsey/pg_featureserv:20241104
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}
      - PGFS_WEBSITE_BASEMAPURL=https://tile.openstreetmap.de/{z}/{x}/{y}.png
      - PGFS_PAGING_LIMITDEFAULT=100
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgis/postgis:16-3.4
    hostname: ${PGHOST}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data:/data
    environment:
      # required to initialize database
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      # required to be able to queries in psql
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s

  osm2pgsql:
    image: iboates/osm2pgsql:2.0.1
    environment:
      - PGHOST
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    volumes:
      - ./data:/data
    command: exit
    depends_on:
      postgres:
        condition: service_healthy

  web-client:
    build: ./web-client
    ports:
      - "4173:4173"
