services:
  api:
    image: pramsey/pg_featureserv
    ports:
      - "0.0.0.0:${PG_FEATURESERV_SYSTEM_PORT}:9000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgis/postgis:latest
    ports:
      - "0.0.0.0:${DB_SYSTEM_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data:/data
    env_file:
      - .env
  osm2pgsql:
    image: iboates/osm2pgsql:latest
    env_file:
      - .env
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: