name: test-setup

on:
    push:
      branches: [test-setup-ci]

jobs:
    run-setup-on-ubuntu:
        name: Run npm on Ubuntu
        runs-on: ubuntu-24.04
        steps:
            - name: Install packages
              run: |
                sudo apt-get update
                sudo apt-get install -y postgresql wait-for-it

            - name: Start PostgreSQL service
              run: |
                sudo service postgresql start
                sudo -u postgres psql -c "CREATE USER myuser WITH PASSWORD 'mypassword';"
                sudo -u postgres psql -c "CREATE DATABASE mydatabase OWNER myuser;"

            - name: Wait for PostgreSQL
              run: wait-for-it localhost:5432 -t 30 -- echo "PostgreSQL is ready!"

            - name: Run SQL commands
              run: |
                PGPASSWORD=mypassword psql -h localhost -U myuser -d mydatabase -c "SELECT 'Hello, PostgreSQL!' AS greeting;"
